# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      leakDetectionThreshold: 300000

# core
core:
  security-policy: AUTHENTICATED

# web
web:
  brand: <img class="icon" src="/static/image/logo-fintics.png"/>
  title: Fintics
  index: monitor

# fintics
fintics:
  client:
    indice:
      class-name: org.oopscraft.fintics.client.indice.YahooIndiceClient
  collector:
    enabled: true
    indice-collector:
      ohlcv-retention-months: 1
    trade-collector:
      ohlcv-retention-months: 1
