# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      leakDetectionThreshold: 300000

# web
web:
  brand: <img class="icon" src="/static/image/logo-fintics.png"/>
  title: Fintics
  index: monitors
  security-policy: AUTHENTICATED

# fintics
fintics:
  system-alarm-id: fintics
  ohlcv-retention-months: 3
  indice-client:
    class-name: org.oopscraft.fintics.client.indice.yahoo.YahooIndiceClient
    properties:
      name: value
  ohlcv-client:
    class-name: org.oopscraft.fintics.client.ohlcv.yahoo.YahooOhlcvClient
    properties:
      name: value

