# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30

# web
web:
  brand: <img class="icon" src="/static/image/logo-fintics.png"/>
  title: Fintics
  index: monitor
  security-policy: ~
  locales:
    - en_US
    - ko_KR

# fintics
fintics:
  client:
    asset:
      class-name: org.oopscraft.fintics.client.asset.SeibroAssetClient
    market:
      class-name: org.oopscraft.fintics.client.market.YahooMarketClient
  collector:
    asset-collector:
      limit: 100
    indice-collector:
      ohlcv-retention-months: 1
    trade-collector:
      ohlcv-retention-months: 1
