# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      leakDetectionThreshold: 300000

# web
web:
  brand: <img class="icon" src="/static/image/logo-fintics.png"/>
  title: Fintics
  index: monitor
  security-policy: AUTHENTICATED

# fintics
fintics:
  system-alarm-id: fintics
  indice-client-class-name: org.oopscraft.fintics.client.indice.YahooIndiceClient
  ohlcv-retention-months: 12
