# logging
logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp.stomp: DEBUG

# server
server:
  tomcat:
    threads:
      max: 200
      min-spare: 100

# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      leakDetectionThreshold: 300000

# web
web:
  brand: <img src="/static/image/fintics-icon.svg"/><img src="/static/image/fintics-title.svg"/>
  favicon: /static/image/fintics-icon.svg
  title: Fintics
  index: monitors
  security-policy: AUTHENTICATED

# fintics
fintics:
  system-alarm-id: fintics
  data-retention-months: 3
  asset-client:
    class-name: org.chomookun.fintics.client.asset.SimpleAssetClient
    properties:
      name: value
  ohlcv-client:
    class-name: org.chomookun.fintics.client.ohlcv.SimpleOhlcvClient
    properties:
      name: value
  dividend-client:
    class-name: org.chomookun.fintics.client.dividend.SimpleDividendClient
    properties:
      name: value

