# web
web:
  brand: <img class="icon" src="/static/image/logo-fintics.png"/>
  index: trade
  security-policy: ~
  locales:
    - en_US
    - ko_KR

# fintics
fintics:
  scheduler:
    asset-collect-scheduler:
      limit: 100
