# web
web:
  brand: <img class="icon" src="/static/image/logo-fintics.png"/>
  index: trade
  security-policy: ~
  locales:
    - en_US
    - ko_KR

# fintics
fintics:
  client:
    asset:
      class-name: org.oopscraft.fintics.client.asset.SeibroAssetClient
    market:
      class-name: org.oopscraft.fintics.client.market.YahooMarketClient
  collector:
    asset-collector:
      limit: 100
