# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      leakDetectionThreshold: 300000

# web
web:
  brand: <img class="icon" src="/static/image/logo-fintics.png"/>
  title: Fintics
  index: monitors
  security-policy: AUTHENTICATED

# fintics
fintics:
  system-alarm-id: fintics
  ai-api-url: ~
  data-retention-months: 3
  asset-client:
    class-name: org.oopscraft.fintics.client.asset.SimpleAssetClient
    properties:
      name: value
  ohlcv-client:
    class-name: org.oopscraft.fintics.client.ohlcv.SimpleOhlcvClient
    properties:
      name: value
  news-client:
    class-name: org.oopscraft.fintics.client.news.SimpleNewsClient
    properties:
      name: value
